import {QueryClient,QueryClientProvider,useQuery} from "@tanstack/react-query";
import {ReactFlowProvider,ReactFlow,Background,BackgroundVariant,Controls,useEdgesState,useNodesState,useReactFlow,type Edge,type NodeTypes,type OnNodesDelete} from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import {useCallback,useEffect,useMemo} from "react";
import {getApps,getGraph} from "./api";
import {useUI} from "./store";
import type {ServiceNode} from "./types";
import {AppPanel,Inspector,LeftRail,ServiceCard,TopBar} from "./components";

const qc=new QueryClient();
const nodeTypes:NodeTypes={serviceCard:ServiceCard};

function Canvas({nodes,edges,setNodes,setEdges,onNodesChange,onEdgesChange,graph,loading,error,refetch}:{nodes:ServiceNode[];edges:Edge[];setNodes:React.Dispatch<React.SetStateAction<ServiceNode[]>>;setEdges:React.Dispatch<React.SetStateAction<Edge[]>>;onNodesChange:any;onEdgesChange:any;graph?:{nodes:ServiceNode[];edges:Edge[]};loading:boolean;error:Error|null;refetch:()=>void}){const selected=useUI(s=>s.selectedNodeId),setSelected=useUI(s=>s.setSelectedNodeId),fitToken=useUI(s=>s.fitToken),{fitView}=useReactFlow();useEffect(()=>{if(graph){setNodes(graph.nodes);setEdges(graph.edges);setTimeout(()=>fitView({padding:.18,duration:600}),60)}},[graph,setNodes,setEdges,fitView]);useEffect(()=>{if(fitToken)fitView({padding:.18,duration:500})},[fitToken,fitView]);const visible=useMemo(()=>nodes.map(n=>({...n,selected:n.id===selected})),[nodes,selected]);const onDel:OnNodesDelete<ServiceNode>=(deleted)=>{if(deleted.some(n=>n.id===selected))setSelected(null)};if(loading)return <div className="center-state"><div className="loader"/>Loading graph...</div>;if(error)return <div className="center-state error-state"><h2>Graph API Error</h2><p>{error.message}</p><button className="btn blue" onClick={refetch}>Retry</button></div>;return <ReactFlow nodes={visible} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onNodeClick={(_,n)=>setSelected(n.id)} onPaneClick={()=>setSelected(null)} onNodesDelete={onDel} deleteKeyCode={["Delete","Backspace"]} minZoom={.3} maxZoom={1.4} fitView><Background variant={BackgroundVariant.Dots} gap={24} size={1.6} color="#2c2f35"/><Controls position="bottom-right"/></ReactFlow>}

function Builder(){const appId=useUI(s=>s.selectedAppId),selectedId=useUI(s=>s.selectedNodeId),setSelected=useUI(s=>s.setSelectedNodeId),errorMode=useUI(s=>s.errorMode),theme=useUI(s=>s.theme);const apps=useQuery({queryKey:["apps"],queryFn:getApps});const graph=useQuery({queryKey:["graph",appId,errorMode],queryFn:()=>getGraph(appId,errorMode)});const [nodes,setNodes,onNodesChange]=useNodesState<ServiceNode>([]);const [edges,setEdges,onEdgesChange]=useEdgesState<Edge>([]);const selectedNode=useMemo(()=>nodes.find(n=>n.id===selectedId)||null,[nodes,selectedId]);const updateNode=useCallback((id:string,patch:Partial<ServiceNode["data"]>)=>setNodes(cur=>cur.map(n=>n.id===id?{...n,data:{...n.data,...patch}}:n)),[setNodes]);const addNode=useCallback(()=>{const id=`node-${Date.now()}`;setNodes(cur=>[...cur,{id,type:"serviceCard",position:{x:520,y:420},data:{label:"New Service",status:"Success",cpu:2,memory:"0.05 GB",disk:"10.00 GB",region:"1",description:"Added from + button",icon:"app"}}]);setSelected(id)},[setNodes,setSelected]);const deleteNode=useCallback(()=>{if(!selectedId)return;setNodes(cur=>cur.filter(n=>n.id!==selectedId));setEdges(cur=>cur.filter(e=>e.source!==selectedId&&e.target!==selectedId));setSelected(null)},[selectedId,setNodes,setEdges,setSelected]);useEffect(()=>{const root=document.documentElement;root.classList.toggle("theme-light",theme==="light");root.classList.toggle("theme-dark",theme==="dark");},[theme]);return <div className="app-root"><TopBar/><LeftRail/><AppPanel apps={apps.data} loading={apps.isLoading} onAddNode={addNode}/><main className="canvas"><Canvas graph={graph.data} loading={graph.isLoading} error={graph.error} nodes={nodes} edges={edges} setNodes={setNodes} setEdges={setEdges} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} refetch={()=>void graph.refetch()}/></main><Inspector node={selectedNode} updateNode={updateNode} deleteNode={deleteNode}/></div>}

export default function App(){return <QueryClientProvider client={qc}><ReactFlowProvider><Builder/></ReactFlowProvider></QueryClientProvider>}
