import {Briefcase,ChevronRight,Cpu,Database,GitBranch,Grid2X2,HardDrive,Lightbulb,MapPin,Moon,Network,PanelRightOpen,Puzzle,Rocket,Search,Server,Settings,Share2,Sun,X} from "lucide-react";
import {Handle,Position,type NodeProps} from "@xyflow/react";
import {useUI} from "./store";
import type {AppSummary,ServiceNode,Status} from "./types";

export function Button(p:React.ButtonHTMLAttributes<HTMLButtonElement>&{v?:"blue"|"dark"|"ghost"|"danger";s?:"icon"|"md"}){return <button {...p} className={`btn ${p.v||"dark"} ${p.s==="icon"?"icon":""} ${p.className||""}`}/>}

export function TopBar(){const fit=useUI(s=>s.requestFit),open=useUI(s=>s.setMobilePanelOpen),setTheme=useUI(s=>s.setTheme);const handleShare=()=>{navigator.clipboard?.writeText(window.location.href).then(()=>alert("Page URL copied"),()=>alert("Unable to copy URL"));};return <><div className="top-actions"><Button s="icon" onClick={handleShare}><Share2 size={18}/></Button><Button s="icon" onClick={()=>setTheme("dark")} title="Dark mode"><Moon size={18}/></Button><Button s="icon" onClick={()=>setTheme("light")} title="Light mode"><Sun size={18}/></Button><div className="avatar">🧑‍💻</div><Button className="mobile-panel-btn" s="icon" v="blue" onClick={()=>open(true)}><PanelRightOpen size={18}/></Button></div></>}

export function LeftRail(){return <nav className="left-rail"><button className="rail-button postgres-mini"><Database size={24}/></button><button className="rail-button redis-mini"><Server size={24}/></button><button className="rail-button"><GitBranch size={23}/></button><button className="rail-button yellow"><Grid2X2 size={24}/></button><button className="rail-button green"><Network size={25}/></button></nav>}

const iconMap={bulb:Lightbulb,gear:Settings,rocket:Rocket,bag:Briefcase,puzzle:Puzzle};
export function AppPanel({apps,loading,onAddNode}:{apps?:AppSummary[];loading:boolean;onAddNode:()=>void}){const selected=useUI(s=>s.selectedAppId),set=useUI(s=>s.setSelectedAppId);return <aside className="app-panel"><h2>Application</h2><div className="search-row"><div className="search-wrap"><input placeholder="Search..."/><Search size={21}/></div><Button v="blue" s="icon" onClick={onAddNode}>+</Button></div><div className="apps-list">{loading&&Array.from({length:5}).map((_,i)=><div className="app-skeleton" key={i}/>) }{apps?.map(app=>{const Icon=iconMap[app.icon];return <button key={app.id} className={`app-item ${selected===app.id?"selected":""}`} onClick={()=>set(app.id)}><span className={`app-icon ${app.icon}`}><Icon size={23}/></span><strong>{app.name}</strong><ChevronRight size={23}/></button>})}</div></aside>}

function IconBadge({icon}:{icon:ServiceNode["data"]["icon"]}){if(icon==="postgres")return <span className="node-logo postgres">🐘</span>;if(icon==="redis")return <span className="node-logo redis">▰</span>;if(icon==="mongo")return <span className="node-logo mongo">⬢</span>;return <span className="node-logo app">◩</span>}
export function ServiceCard({data,selected}:NodeProps<ServiceNode>){return <div className={`service-node ${selected?"selected":""}`}><Handle type="target" position={Position.Left} className="handle"/><div className="node-head"><div className="node-title"><IconBadge icon={data.icon}/><strong>{data.label}</strong></div><div className="node-actions"><span className="price">$0.03/HR</span><span className="gear"><Settings size={20}/></span></div></div><div className="node-metrics"><span>{(data.cpu/100).toFixed(2)}</span><span>{data.memory}</span><span>{data.disk}</span><span>{data.region}</span></div><div className="node-tabs"><span className="tab active"><Cpu size={15}/>CPU</span><span className="tab"><Database size={15}/>Memory</span><span className="tab"><HardDrive size={15}/>Disk</span><span className="tab"><MapPin size={15}/>Region</span></div><div className="slider-row"><div className="fake-slider"/><span className="num-box">{(data.cpu/100).toFixed(2)}</span></div><div className="node-bottom"><span className={`status ${data.status.toLowerCase()}`}>{data.status==="Success"?"✓":"⚠"} {data.status}</span><span className="aws">AWS</span></div><Handle type="source" position={Position.Right} className="handle"/></div>}

export function Inspector({node,updateNode,deleteNode}:{node:ServiceNode|null;updateNode:(id:string,patch:Partial<ServiceNode["data"]>)=>void;deleteNode:()=>void}){const open=useUI(s=>s.isMobilePanelOpen),setOpen=useUI(s=>s.setMobilePanelOpen),tab=useUI(s=>s.tab),setTab=useUI(s=>s.setTab),error=useUI(s=>s.errorMode),setError=useUI(s=>s.setErrorMode);return <><div className={`drawer-backdrop ${open?"show":""}`} onClick={()=>setOpen(false)}/><aside className={`inspector ${open?"show":""}`}><div className="inspector-head"><div><p>Node Inspector</p><h3>{node?node.data.label:"No node selected"}</h3></div><Button v="ghost" s="icon" onClick={()=>setOpen(false)}><X size={20}/></Button></div>{!node?<div className="empty-inspector">Select any node from canvas to edit config.</div>:<><span className={`big-status ${node.data.status.toLowerCase()}`}>{node.data.status}</span><div className="inspector-tabs">{(["cpu","memory","disk","region"] as const).map(t=><button className={tab===t?"active":""} key={t} onClick={()=>setTab(t)}>{t.toUpperCase()}</button>)}</div><label>Node name<input value={node.data.label} onChange={e=>updateNode(node.id,{label:e.target.value})}/></label><label>Description<textarea value={node.data.description} onChange={e=>updateNode(node.id,{description:e.target.value})}/></label><label>Status<select value={node.data.status} onChange={e=>updateNode(node.id,{status:e.target.value as Status})}><option>Success</option><option>Error</option><option>Warning</option></select></label><label>CPU Slider + Input<div className="cpu-sync"><input type="range" min="0" max="100" value={node.data.cpu} onChange={e=>updateNode(node.id,{cpu:Number(e.target.value)})}/><input type="number" min="0" max="100" value={node.data.cpu} onChange={e=>updateNode(node.id,{cpu:Math.max(0,Math.min(100,Number(e.target.value)))})}/></div></label><label className="checkbox-line"><input type="checkbox" checked={error} onChange={e=>setError(e.target.checked)}/> Simulate TanStack Query error</label><Button v="danger" onClick={deleteNode}>Delete selected node</Button></>}</aside></>}
